-- Generated by SQL Maestro for MySQL. Release date 08/04/2010
-- 09/06/2010 21:35:45
-- ----------------------------------
-- Alias: rejoc1 at localhost
-- Database name: rejoc1
-- Host: localhost
-- Port number: 3306
-- User name: root
-- Server: 5.0.51b-community
-- Session ID: 73
-- Character set: latin1
-- Collation: latin1_swedish_ci
-- Client encoding: latin1


SET FOREIGN_KEY_CHECKS=0;

CREATE DATABASE `rejoc1`
  CHARACTER SET `latin1`
  COLLATE `latin1_swedish_ci`;

USE `rejoc1`;

/* Tables */
CREATE TABLE `cidades` (
  `idcidade`  int(10) UNSIGNED AUTO_INCREMENT NOT NULL,
  `cid_nome`  varchar(25),
  PRIMARY KEY (`idcidade`)
) ENGINE = InnoDB;

CREATE TABLE `equipes` (
  `idequipes`  int(10) UNSIGNED AUTO_INCREMENT NOT NULL,
  `equ_nome`   varchar(30),
  PRIMARY KEY (`idequipes`)
) ENGINE = InnoDB;

CREATE TABLE `estados` (
  `idestados`  int(10) UNSIGNED AUTO_INCREMENT NOT NULL,
  `est_sigla`  varchar(2),
  PRIMARY KEY (`idestados`)
) ENGINE = InnoDB;

CREATE TABLE `pessoas` (
  `idpessoas`        int(10) UNSIGNED AUTO_INCREMENT NOT NULL,
  `pes_cod_equipes`  int(10) UNSIGNED NOT NULL,
  `pes_cod_estados`  int(10) UNSIGNED NOT NULL,
  `pes_cod_cidade`   int(10) UNSIGNED NOT NULL,
  `pes_nome`         varchar(40),
  `pes_dia_nasc`     varchar(2),
  `pes_end`          varchar(50),
  `pes_cep`          varchar(9),
  `pes_fone`         varchar(45),
  `pes_email`        varchar(45),
  `pes_bairro`       varchar(22),
  `pes_mes_nasc`     varchar(2),
  PRIMARY KEY (`idpessoas`)
) ENGINE = InnoDB;

/* Indexes */
CREATE INDEX `pessoas_FKIndex1`
  ON `pessoas`
  (`pes_cod_cidade`);

CREATE INDEX `pessoas_FKIndex2`
  ON `pessoas`
  (`pes_cod_estados`);

CREATE INDEX `pessoas_FKIndex3`
  ON `pessoas`
  (`pes_cod_equipes`);

/* Foreign Keys */
ALTER TABLE `pessoas`
  ADD CONSTRAINT `pessoas_ibfk_1`
  FOREIGN KEY (`pes_cod_cidade`)
    REFERENCES `cidades`(`idcidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE `pessoas`
  ADD CONSTRAINT `pessoas_ibfk_2`
  FOREIGN KEY (`pes_cod_estados`)
    REFERENCES `estados`(`idestados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

ALTER TABLE `pessoas`
  ADD CONSTRAINT `pessoas_ibfk_3`
  FOREIGN KEY (`pes_cod_equipes`)
    REFERENCES `equipes`(`idequipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION;

/* Data for table "cidades" */
INSERT INTO `cidades` (`idcidade`, `cid_nome`) VALUES (1, 'Capão da Canoa');
INSERT INTO `cidades` (`idcidade`, `cid_nome`) VALUES (2, 'Xangri-lá');
INSERT INTO `cidades` (`idcidade`, `cid_nome`) VALUES (3, 'Arroio do Sal');
INSERT INTO `cidades` (`idcidade`, `cid_nome`) VALUES (4, ' ');
COMMIT;


/* Data for table "equipes" */
INSERT INTO `equipes` (`idequipes`, `equ_nome`) VALUES (1, 'Cursista');
INSERT INTO `equipes` (`idequipes`, `equ_nome`) VALUES (2, 'Lider');
INSERT INTO `equipes` (`idequipes`, `equ_nome`) VALUES (3, 'Apresentador');
INSERT INTO `equipes` (`idequipes`, `equ_nome`) VALUES (4, '  ');
INSERT INTO `equipes` (`idequipes`, `equ_nome`) VALUES (5, 'Orientação do REJOC');
INSERT INTO `equipes` (`idequipes`, `equ_nome`) VALUES (6, 'Secretaria');
COMMIT;


/* Data for table "estados" */
INSERT INTO `estados` (`idestados`, `est_sigla`) VALUES (1, 'RS');
INSERT INTO `estados` (`idestados`, `est_sigla`) VALUES (2, 'SC');
INSERT INTO `estados` (`idestados`, `est_sigla`) VALUES (3, 'PR');
INSERT INTO `estados` (`idestados`, `est_sigla`) VALUES (4, 'SP');
COMMIT;


/* Data for table "pessoas" */
INSERT INTO `pessoas` (`idpessoas`, `pes_cod_equipes`, `pes_cod_estados`, `pes_cod_cidade`, `pes_nome`, `pes_dia_nasc`, `pes_end`, `pes_cep`, `pes_fone`, `pes_email`, `pes_bairro`, `pes_mes_nasc`) VALUES (1, 5, 1, 2, 'Neuza Beatriz dos Santos Réus', '15', 'Rua Andina Norberta de Matos, 190', '95588-000', '(51) 3689-6050', '.', 'Guará', '03');
INSERT INTO `pessoas` (`idpessoas`, `pes_cod_equipes`, `pes_cod_estados`, `pes_cod_cidade`, `pes_nome`, `pes_dia_nasc`, `pes_end`, `pes_cep`, `pes_fone`, `pes_email`, `pes_bairro`, `pes_mes_nasc`) VALUES (2, 1, 1, 1, 'Adalto Selau Sparremberger', '05', 'Rua dos Narcisos, 3652', '95555-000', '(51) 3621-1015 / 9215-2684', 'adalto@adalto.net', 'Capão Novo', '02');
INSERT INTO `pessoas` (`idpessoas`, `pes_cod_equipes`, `pes_cod_estados`, `pes_cod_cidade`, `pes_nome`, `pes_dia_nasc`, `pes_end`, `pes_cep`, `pes_fone`, `pes_email`, `pes_bairro`, `pes_mes_nasc`) VALUES (3, 1, 1, 3, 'João Carlos Santos', '01', 'Rua cdfddsfdsvdsf', '95555-000', '(51) 236252654', 'ccdsfdfgv@wsfdfdsfdd.com.br', 'sfsdfsddsv', '01');
INSERT INTO `pessoas` (`idpessoas`, `pes_cod_equipes`, `pes_cod_estados`, `pes_cod_cidade`, `pes_nome`, `pes_dia_nasc`, `pes_end`, `pes_cep`, `pes_fone`, `pes_email`, `pes_bairro`, `pes_mes_nasc`) VALUES (4, 1, 1, 2, 'Tia Neusa', '15', 'Rua fdfdsf', '95588-000', '(51) 36252515251425', 'tianeuza@adalto.net', 'Guará', '03');
INSERT INTO `pessoas` (`idpessoas`, `pes_cod_equipes`, `pes_cod_estados`, `pes_cod_cidade`, `pes_nome`, `pes_dia_nasc`, `pes_end`, `pes_cep`, `pes_fone`, `pes_email`, `pes_bairro`, `pes_mes_nasc`) VALUES (5, 1, 1, 2, 'Zé Carlos', '01', 'Av Central, 361616', '95588-000', '(51) 65656456464', 'podredexique@adalto.net', 'Atlantida', '01');
INSERT INTO `pessoas` (`idpessoas`, `pes_cod_equipes`, `pes_cod_estados`, `pes_cod_cidade`, `pes_nome`, `pes_dia_nasc`, `pes_end`, `pes_cep`, `pes_fone`, `pes_email`, `pes_bairro`, `pes_mes_nasc`) VALUES (6, 1, 1, 2, 'Cabeludo da Galiléia', '25', 'Ceu. s/n', '00000-000', '(51) 112233445566778899', 'eleeocara@adalto.net', 'xxxxxx', '12');
COMMIT;



























-- phpMyAdmin SQL Dump
-- version 2.11.7
-- http://www.phpmyadmin.net
--
-- Servidor: localhost
-- Tempo de Geração: Jun 14, 2010 as 03:30 PM
-- Versão do Servidor: 5.0.51
-- Versão do PHP: 5.2.6

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- Banco de Dados: `rejoc1`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `cidades`
--

DROP TABLE IF EXISTS `cidades`;
CREATE TABLE IF NOT EXISTS `cidades` (
  `idcidade` int(10) unsigned NOT NULL auto_increment,
  `cid_nome` varchar(25) default NULL,
  PRIMARY KEY  (`idcidade`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

--
-- Extraindo dados da tabela `cidades`
--

INSERT INTO `cidades` (`idcidade`, `cid_nome`) VALUES
(1, 'Capão da Canoa'),
(2, 'Xangri-lá'),
(3, 'Arroio do Sal'),
(4, ' ');

-- --------------------------------------------------------

--
-- Estrutura da tabela `equipes`
--

DROP TABLE IF EXISTS `equipes`;
CREATE TABLE IF NOT EXISTS `equipes` (
  `idequipes` int(10) unsigned NOT NULL auto_increment,
  `equ_nome` varchar(30) default NULL,
  PRIMARY KEY  (`idequipes`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=7 ;

--
-- Extraindo dados da tabela `equipes`
--

INSERT INTO `equipes` (`idequipes`, `equ_nome`) VALUES
(1, 'Cursista'),
(2, 'Lider'),
(3, 'Apresentador'),
(4, '  '),
(5, 'Orientação do REJOC'),
(6, 'Secretaria');

-- --------------------------------------------------------

--
-- Estrutura da tabela `estados`
--

DROP TABLE IF EXISTS `estados`;
CREATE TABLE IF NOT EXISTS `estados` (
  `idestados` int(10) unsigned NOT NULL auto_increment,
  `est_sigla` varchar(2) default NULL,
  PRIMARY KEY  (`idestados`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

--
-- Extraindo dados da tabela `estados`
--

INSERT INTO `estados` (`idestados`, `est_sigla`) VALUES
(1, 'RS'),
(2, 'SC'),
(3, 'PR'),
(4, 'SP');

-- --------------------------------------------------------

--
-- Estrutura da tabela `pessoas`
--

DROP TABLE IF EXISTS `pessoas`;
CREATE TABLE IF NOT EXISTS `pessoas` (
  `idpessoas` int(10) unsigned NOT NULL auto_increment,
  `pes_cod_equipes` int(10) unsigned NOT NULL,
  `pes_cod_estados` int(10) unsigned NOT NULL,
  `pes_cod_cidade` int(10) unsigned NOT NULL,
  `pes_nome` varchar(40) default NULL,
  `pes_dia_nasc` varchar(2) default NULL,
  `pes_end` varchar(50) default NULL,
  `pes_cep` varchar(9) default NULL,
  `pes_fone` varchar(45) default NULL,
  `pes_email` varchar(45) default NULL,
  `pes_bairro` varchar(22) default NULL,
  `pes_mes_nasc` varchar(2) default NULL,
  PRIMARY KEY  (`idpessoas`),
  KEY `pessoas_FKIndex1` (`pes_cod_cidade`),
  KEY `pessoas_FKIndex2` (`pes_cod_estados`),
  KEY `pessoas_FKIndex3` (`pes_cod_equipes`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=14 ;

--
-- Extraindo dados da tabela `pessoas`
--

INSERT INTO `pessoas` (`idpessoas`, `pes_cod_equipes`, `pes_cod_estados`, `pes_cod_cidade`, `pes_nome`, `pes_dia_nasc`, `pes_end`, `pes_cep`, `pes_fone`, `pes_email`, `pes_bairro`, `pes_mes_nasc`) VALUES
(1, 5, 1, 2, 'Neuza Beatriz dos Santos Réus', '15', 'Rua Andina Norberta de Matos, 190', '95588-000', '(51) 3689-6050', '.', 'Guará', '03'),
(2, 1, 1, 1, 'Adalto Selau Sparremberger', '05', 'Rua dos Narcisos, 3652', '95555-000', '(51) 3621-1015 / 9215-2684', 'adalto@adalto.net', 'Capão Novo', '02'),
(3, 1, 1, 3, 'João Carlos Santos', '01', 'Rua cdfddsfdsvdsf', '95555-000', '(51) 236252654', 'ccdsfdfgv@wsfdfdsfdd.com.br', 'sfsdfsddsv', '01'),
(4, 1, 1, 2, 'Tia Neusa', '15', 'Rua fdfdsf', '95588-000', '(51) 36252515251425', 'tianeuza@adalto.net', 'Guará', '03'),
(5, 1, 1, 2, 'Zé Carlos', '01', 'Av Central, 361616', '95588-000', '(51) 65656456464', 'podredexique@adalto.net', 'Atlantida', '01'),
(6, 1, 1, 2, 'Cabeludo da Galiléia', '25', 'Ceu. s/n', '00000-000', '(51) 112233445566778899', 'eleeocara@adalto.net', 'xxxxxx', '12'),
(7, 1, 1, 1, 'Júlia Cezar Sparremberger', '18', 'Rua dos Narcisos, 3640', '95555-000', '(51) 3621-1015', 'julia@adalto.net', 'Capão Novo', '10'),
(8, 1, 1, 3, 'lucas teste1', '01', 'Rua dsdiknibin', '95000-000', '(51) 12523955154515125', 'teste@teste.com', 'Centro', '01'),
(9, 1, 1, 2, 'Teste 33525414125', '01', 'Rua xxxxxxxxxxxxxxxxx, 12540', '90000-000', '(51) 52581151616116', 'teste3625125@teste.com', 'centro', '11'),
(10, 1, 1, 1, 'Suzy', '17', 'Rua dos Narcisos, 3640', '95555-000', '(51) 96697121', 'suzynha@adalto.net', 'Capão Novo', '06'),
(11, 1, 1, 3, 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', '01', 'xxxxxxxxxxxxxxxxxxxxxxxxxxx', '00000-000', '(51) 0000-0000', 'xxxxx@xxxx.xxx.xx', 'xxxxxxxxxxxxxxxxxxxxxx', '01'),
(12, 6, 1, 4, 'aaaaaabbbbbbbbbb', '', '', '-', '() ', '', '', ''),
(13, 6, 1, 4, 'pedro xxxxxxxxxxsjdfnksin', '', '', '-', '() ', '', '', '');

--
-- Restrições para as tabelas dumpadas
--

--
-- Restrições para a tabela `pessoas`
--
ALTER TABLE `pessoas`
  ADD CONSTRAINT `pessoas_ibfk_1` FOREIGN KEY (`pes_cod_cidade`) REFERENCES `cidades` (`idcidade`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `pessoas_ibfk_2` FOREIGN KEY (`pes_cod_estados`) REFERENCES `estados` (`idestados`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `pessoas_ibfk_3` FOREIGN KEY (`pes_cod_equipes`) REFERENCES `equipes` (`idequipes`) ON DELETE NO ACTION ON UPDATE NO ACTION;
